ALTER FUNCTION FN_TOPSALE() RETURNS @RESULT TABLE (PID VARCHAR(50), TOTAL INT) AS
BEGIN
	DECLARE @TEMP TABLE(PID VARCHAR(50), AMT INT)
	INSERT INTO @TEMP SELECT ProductID, SUM(Amount) FROM dbo.Cart_Product GROUP BY ProductID;
	INSERT INTO @RESULT SELECT TOP 10 PID, MAX(AMT) AS TOTAL FROM @TEMP GROUP BY PID ORDER BY TOTAL DESC;
	RETURN
END

SELECT * FROM FN_TOPSALE()