//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoseFashionBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public string BillID { get; set; }
        public string CartID { get; set; }
        public string ReceiverName { get; set; }
        public string ReceiverPhone { get; set; }
        public string DeliveryAddress { get; set; }
        public string ProvinceID { get; set; }
        public string DistrictID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string DiscountCode { get; set; }
        public long TotalPrice { get; set; }
        public long DeliveryFee { get; set; }
        public string Status { get; set; }
    
        public virtual Cart Cart { get; set; }
        public virtual Discount Discount { get; set; }
        public virtual District District { get; set; }
        public virtual Province Province { get; set; }
    }
}
