//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoseFashionBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public string BillID { get; set; }
        public string CartID { get; set; }
        public System.DateTime Date { get; set; }
        public string DiscountCode { get; set; }
    
        public virtual Cart Cart { get; set; }
        public virtual Discount Discount { get; set; }
    }
}
