//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoseFashionBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public string UserID { get; set; }
        public string ProductID { get; set; }
        public double Star { get; set; }
        public string Comment { get; set; }
        public string Title { get; set; }
        public System.DateTime RatingDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual Product Product { get; set; }
    }
}
